import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const redHatText = localFont({
  src: "./fonts/RedHatText-VariableFont_wght.ttf",
  variable: "--font-primary",
  weight: "400 600 700"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${redHatText.variable} antialiased`}>{children}</body>
    </html>
  );
}
